# Generated by Django 4.2.14 on 2025-01-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCPNFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cpn_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedOCEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_file', models.FileField(upload_to='ocel_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpn_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpn_app.uploadedcpnfile')),
            ],
        ),
    ]
