# Generated by Django 4.2.14 on 2025-01-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpn_app', '0002_uploadedcpnfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedcpnfile',
            name='user',
        ),
    ]
